<?xml version="1.0" encoding="UTF-8"?>
<xs:schema
  xmlns:xs="http://www.w3.org/2001/XMLSchema"
  targetNamespace="http://www.loc.gov/MARC21/slim"
  xmlns:marc="http://www.loc.gov/MARC21/slim"
  elementFormDefault="qualified">

  <xs:simpleType name="nonEmptyString">
    <xs:restriction base="xs:string">
      <xs:minLength value="1"/>
    </xs:restriction>
  </xs:simpleType>

  <xs:element name="collection">
    <xs:complexType>
      <xs:sequence>
        <xs:element ref="marc:record" minOccurs="0" maxOccurs="unbounded"/>
      </xs:sequence>
    </xs:complexType>
  </xs:element>

  <xs:element name="record">
    <xs:complexType>
      <xs:sequence>
        <xs:element name="leader" type="xs:string"/>
        <xs:element name="controlfield" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:simpleContent>
              <xs:extension base="xs:string">
                <xs:attribute name="tag" type="marc:nonEmptyString" use="required"/>
              </xs:extension>
            </xs:simpleContent>
          </xs:complexType>
        </xs:element>
        <xs:element name="datafield" minOccurs="0" maxOccurs="unbounded">
          <xs:complexType>
            <xs:sequence>
              <xs:element name="subfield" minOccurs="1" maxOccurs="unbounded">
                <xs:complexType>
                  <xs:simpleContent>
                    <xs:extension base="xs:string">
                      <xs:attribute name="code" type="marc:nonEmptyString" use="required"/>
                    </xs:extension>
                  </xs:simpleContent>
                </xs:complexType>
              </xs:element>
            </xs:sequence>
            <xs:attribute name="tag" type="marc:nonEmptyString" use="required"/>
            <xs:attribute name="ind1" type="marc:nonEmptyString" use="required"/>
            <xs:attribute name="ind2" type="marc:nonEmptyString" use="required"/>
          </xs:complexType>
        </xs:element>
      </xs:sequence>
    </xs:complexType>
  </xs:element>
</xs:schema>
